// Copyright 2026 Alibaba Group
// Licensed under the Apache License, Version 2.0 (the "License");

// Code generated by cmd_param_aliases; DO NOT EDIT.
// Source: internal/cli/param_concepts.json reduced against the live Cobra tree.
// Regenerate with `make generate-schema` (or `go generate ./internal/cli`).

package cli

// generatedParamAliases is the per-command parameter-alias table reduced from
// the reviewed concept dictionary. Each entry binds one runnable Cobra leaf.
var generatedParamAliases = []ParamAliasEntry{
	{
		CLIPath: "aitable +base-search",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "aitable +field-get",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable +list-tables",
		Aliases: map[string]string{
			"base-id":    "base",
			"base-token": "base",
		},
	},
	{
		CLIPath: "aitable +record-query",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable +record-share-url",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable +table-get",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable record query",
		Aliases: map[string]string{
			"max-result":  "limit",
			"max-results": "limit",
			"per-page":    "limit",
			"size":        "limit",
			"take":        "limit",
			"top":         "limit",
		},
		Blocked: []string{"count", "page"},
	},
	{
		CLIPath: "attendance +check-result",
		Aliases: map[string]string{
			"user-ids": "users",
		},
		Blocked: []string{"at-user-ids", "staff-id", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "attendance check result",
		Aliases: map[string]string{
			"user-ids": "users",
		},
		Blocked: []string{"at-user-ids", "staff-id", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "calendar event list",
		Aliases: map[string]string{
			"begin":           "start",
			"date":            "start",
			"from":            "start",
			"from-date":       "start",
			"max-result":      "limit",
			"next-page-token": "cursor",
			"per-page":        "limit",
			"since":           "start",
			"take":            "limit",
			"top":             "limit",
		},
		Blocked: []string{"offset", "page", "time"},
	},
	{
		CLIPath: "chat +bot-find",
		Aliases: map[string]string{
			"name": "query",
		},
	},
	{
		CLIPath: "chat +bot-search",
		Aliases: map[string]string{
			"current-page": "page",
			"query":        "name",
		},
		Blocked: []string{"cursor"},
	},
	{
		CLIPath: "chat +category-create",
		Aliases: map[string]string{
			"name": "title",
		},
	},
	{
		CLIPath: "chat +category-delete",
		Blocked: []string{"category-ids"},
	},
	{
		CLIPath: "chat +category-rename",
		Aliases: map[string]string{
			"name": "title",
		},
		Blocked: []string{"category-ids"},
	},
	{
		CLIPath: "chat +chat-bots",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-dismiss",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-invite-url",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-mute",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-role-add",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-role-list",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-role-query-user",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"uid":                  "user",
			"user-id":              "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat +chat-role-set-user",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"uid":                  "user",
			"user-id":              "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "role-id", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat +chat-role-update",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "open-conversation-ids", "role-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-set-admin",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "open-dingtalk-id", "source", "src-conversation-id", "target", "user-id"},
	},
	{
		CLIPath: "chat +chat-set-history",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-update-alias",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +chat-update-nick",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +conversation-info",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "staff-id", "target", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "chat +group-members",
		Aliases: map[string]string{
			"group-name": "group",
		},
		Blocked: []string{"chat-id", "conversation-id", "group-id", "id", "open-conversation-id"},
	},
	{
		CLIPath: "chat +messages-list-direct",
		Aliases: map[string]string{
			"staff-id": "user",
			"start":    "time",
			"uid":      "user",
			"user-id":  "user",
			"userid":   "user",
		},
		Blocked: []string{"at-user-ids", "end", "name", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat +messages-list-pin",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat +messages-list-unread-conversations",
		Aliases: map[string]string{
			"limit": "count",
			"size":  "count",
		},
	},
	{
		CLIPath: "chat +messages-mget",
		Aliases: map[string]string{
			"message-ids":      "msg-ids",
			"open-message-ids": "msg-ids",
		},
		Blocked: []string{"message-id", "msg-id", "open-message-id", "ref-msg-id", "src-msg-id"},
	},
	{
		CLIPath: "chat +messages-read-status",
		Aliases: map[string]string{
			"chat":                 "conversation-id",
			"chat-id":              "conversation-id",
			"msg-id":               "message-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "message-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-dingtalk-id", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id", "user-id"},
	},
	{
		CLIPath: "chat +messages-send-by-webhook",
		Aliases: map[string]string{
			"at-user-ids": "at-users",
		},
	},
	{
		CLIPath: "chat +send-to-group",
		Aliases: map[string]string{
			"group-name": "group",
		},
		Blocked: []string{"chat-id", "conversation-id", "group-id", "id", "open-conversation-id"},
	},
	{
		CLIPath: "chat +unread-chats",
		Aliases: map[string]string{
			"limit": "count",
			"size":  "count",
		},
	},
	{
		CLIPath: "chat bot find",
		Aliases: map[string]string{
			"name": "query",
		},
	},
	{
		CLIPath: "chat bot search",
		Aliases: map[string]string{
			"current-page": "page",
			"query":        "name",
		},
		Blocked: []string{"cursor"},
	},
	{
		CLIPath: "chat category add-conv",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"category-id", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat category create",
		Aliases: map[string]string{
			"name": "title",
		},
	},
	{
		CLIPath: "chat category create-smart",
		Aliases: map[string]string{
			"open-dingtalk-ids": "members",
			"title":             "name",
		},
		Blocked: []string{"staff-id", "user", "user-id", "user-ids", "users"},
	},
	{
		CLIPath: "chat category delete",
		Blocked: []string{"category-ids"},
	},
	{
		CLIPath: "chat category list-conversations",
		Blocked: []string{"category-ids"},
	},
	{
		CLIPath: "chat category remove-conv",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"category-id", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat category rename",
		Aliases: map[string]string{
			"name": "title",
		},
		Blocked: []string{"category-ids"},
	},
	{
		CLIPath: "chat chmod",
		Aliases: map[string]string{
			"chat":                 "conversation-id",
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
			"staff-id":             "user",
			"uid":                  "user",
			"user-id":              "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat clear-messages",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat clear-red-point",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat conversation-info",
		Aliases: map[string]string{
			"chat-id":              "group",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"uid":                  "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat group audit-join-validation",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked:   []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
		Ambiguous: []string{"staff-id", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "chat group bots",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group create",
		Blocked: []string{"open-dingtalk-id", "user-id"},
	},
	{
		CLIPath: "chat group dismiss",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group get-by-group-id",
		Blocked: []string{"chat", "chat-id", "conversation-id", "conversation-ids", "group", "group-name", "id", "name", "open-conversation-id", "open-conversation-ids"},
	},
	{
		CLIPath: "chat group invite-url",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group members",
		Aliases: map[string]string{
			"chat":                 "id",
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group members add",
		Aliases: map[string]string{
			"chat":                 "id",
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "open-dingtalk-id", "source", "src-conversation-id", "target", "user-id"},
	},
	{
		CLIPath: "chat group members add-bot",
		Aliases: map[string]string{
			"chat":                 "id",
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"open-conversation-id": "id",
			"robot":                "robot-code",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "robot-id", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group members list-by-ids",
		Aliases: map[string]string{
			"chat":                 "id",
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"open-conversation-id": "id",
			"open-dingtalk-ids":    "users",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "staff-id", "target", "user", "user-id", "user-ids"},
	},
	{
		CLIPath: "chat group members remove",
		Aliases: map[string]string{
			"chat":                 "id",
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"open-conversation-id": "id",
			"user-ids":             "users",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "staff-id", "target", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "chat group members remove-bot",
		Aliases: map[string]string{
			"chat":                 "id",
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"open-bot-id":          "bot-id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"bot-code", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "robot", "robot-code", "robot-id", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group notice create",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group notice edit",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group notice get",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group notice list",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group quit",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group rename",
		Aliases: map[string]string{
			"chat":                 "id",
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group set-admin",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
			"user-ids":             "users",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "staff-id", "target", "uid", "userid"},
	},
	{
		CLIPath: "chat group set-history",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group share-invite",
		Aliases: map[string]string{
			"source-conversation-id": "source",
			"target-conversation-id": "target",
		},
		Blocked:   []string{"group-id", "group-ids", "staff-id", "uid", "user", "user-id", "userid"},
		Ambiguous: []string{"chat", "chat-id", "conversation-id", "group", "id", "open-conversation-id"},
	},
	{
		CLIPath: "chat group transfer-owner",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"uid":                  "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat group update-alias",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group update-icon",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group update-nick",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group update-settings",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group-mute",
		Aliases: map[string]string{
			"chat-id":              "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group-mute-member",
		Aliases: map[string]string{
			"chat-id":              "group",
			"open-conversation-id": "group",
			"user-ids":             "users",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "staff-id", "target", "uid", "userid"},
	},
	{
		CLIPath: "chat group-role add",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group-role list",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group-role query-user",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"uid":                  "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat group-role remove",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "role-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat group-role remove-user",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"uid":                  "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "role-id", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat group-role set-user",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"uid":                  "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "role-id", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat group-role update",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "open-conversation-ids", "role-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat hide",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat mark-read",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"msg-id":               "message-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "message-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat mark-unread",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat message add-emoji",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"message-id":           "msg-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "msg-id",
		},
		Blocked: []string{"conversation-ids", "group-id", "group-ids", "message-ids", "msg-ids", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "src-msg-id", "topic-id"},
	},
	{
		CLIPath: "chat message add-favorite",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
			"message-id":      "open-message-id",
			"msg-id":          "open-message-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat message add-text-emotion",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"message-id":           "msg-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "msg-id",
		},
		Blocked: []string{"conversation-ids", "group-id", "group-ids", "message-ids", "msg-ids", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "src-msg-id", "topic-id"},
	},
	{
		CLIPath: "chat message combine-forward",
		Aliases: map[string]string{
			"dest-open-cid":               "dest-conversation-id",
			"destination-conversation-id": "dest-conversation-id",
			"message-ids":                 "msg-ids",
			"open-message-ids":            "msg-ids",
			"source-conversation-id":      "src-conversation-id",
			"src-open-cid":                "src-conversation-id",
			"target-conversation-id":      "dest-conversation-id",
		},
		Blocked:   []string{"group-id", "group-ids", "message-id", "msg-id", "open-message-id", "ref-msg-id", "src-msg-id"},
		Ambiguous: []string{"chat", "chat-id", "conversation-id", "group", "id", "open-conversation-id"},
	},
	{
		CLIPath: "chat message download-media",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat message forward",
		Aliases: map[string]string{
			"dest-open-cid":               "dest-conversation-id",
			"destination-conversation-id": "dest-conversation-id",
			"message-id":                  "msg-id",
			"open-message-id":             "msg-id",
			"source-conversation-id":      "src-conversation-id",
			"src-open-cid":                "src-conversation-id",
			"target-conversation-id":      "dest-conversation-id",
		},
		Blocked:   []string{"group-id", "group-ids", "message-ids", "msg-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "src-msg-id", "topic-id"},
		Ambiguous: []string{"chat", "chat-id", "conversation-id", "group", "id", "open-conversation-id"},
	},
	{
		CLIPath: "chat message forward-topic",
		Aliases: map[string]string{
			"dest-open-conversation-id":   "dest-conversation-id",
			"destination-conversation-id": "dest-conversation-id",
			"source-conversation-id":      "src-conversation-id",
			"source-message-id":           "src-msg-id",
			"src-open-conversation-id":    "src-conversation-id",
			"src-open-message-id":         "src-msg-id",
			"target-conversation-id":      "dest-conversation-id",
		},
		Blocked:   []string{"group-id", "group-ids", "message-id", "msg-id", "open-message-id"},
		Ambiguous: []string{"chat", "chat-id", "conversation-id", "group", "id", "open-conversation-id"},
	},
	{
		CLIPath: "chat message list",
		Aliases: map[string]string{
			"chat-id":              "group",
			"max-result":           "limit",
			"max-results":          "limit",
			"open-conversation-id": "group",
			"page-size":            "limit",
			"per-page":             "limit",
			"staff-id":             "user",
			"start":                "time",
			"take":                 "limit",
			"top":                  "limit",
			"uid":                  "user",
			"user-id":              "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "count", "cursor", "dest-conversation-id", "end", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "page", "source", "src-conversation-id", "target", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "chat message list-all",
		Aliases: map[string]string{
			"begin":      "start",
			"from":       "start",
			"from-date":  "start",
			"min-time":   "start",
			"since":      "start",
			"start-date": "start",
			"start-time": "start",
			"time-min":   "start",
		},
		Blocked: []string{"date", "time"},
	},
	{
		CLIPath: "chat message list-by-ids",
		Aliases: map[string]string{
			"message-ids":      "msg-ids",
			"open-message-ids": "msg-ids",
		},
		Blocked: []string{"message-id", "msg-id", "open-message-id", "ref-msg-id", "src-msg-id"},
	},
	{
		CLIPath: "chat message list-by-sender",
		Aliases: map[string]string{
			"open-dingtalk-id": "sender-open-dingtalk-id",
			"user-id":          "sender-user-id",
		},
		Blocked: []string{"time"},
	},
	{
		CLIPath: "chat message list-emotion-replies",
		Aliases: map[string]string{
			"message-ids":      "msg-ids",
			"open-message-ids": "msg-ids",
		},
		Blocked: []string{"message-id", "msg-id", "open-message-id", "ref-msg-id", "src-msg-id"},
	},
	{
		CLIPath: "chat message list-favorites",
		Aliases: map[string]string{
			"limit": "size",
		},
	},
	{
		CLIPath: "chat message list-mentions",
		Aliases: map[string]string{
			"chat-id":              "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat message list-pin-msg",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat message list-topic-replies",
		Aliases: map[string]string{
			"chat-id":              "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat message list-unread-conversations",
		Aliases: map[string]string{
			"limit": "count",
			"size":  "count",
		},
	},
	{
		CLIPath: "chat message read-status",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"msg-id":               "message-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "message-id",
			"user-ids":             "users",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "staff-id", "target", "topic-id", "uid", "userid"},
	},
	{
		CLIPath: "chat message recall",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"message-id":           "msg-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "msg-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat message recall-by-bot",
		Aliases: map[string]string{
			"chat-id":              "group",
			"open-conversation-id": "group",
			"robot":                "robot-code",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "robot-id", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat message remove-emoji",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"message-id":           "msg-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "msg-id",
		},
		Blocked: []string{"conversation-ids", "group-id", "group-ids", "message-ids", "msg-ids", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "src-msg-id", "topic-id"},
	},
	{
		CLIPath: "chat message remove-favorite",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
			"message-id":      "open-message-id",
			"msg-id":          "open-message-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat message remove-text-emotion",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"message-id":           "msg-id",
			"open-conversation-id": "conversation-id",
			"open-message-id":      "msg-id",
		},
		Blocked: []string{"conversation-ids", "group-id", "group-ids", "message-ids", "msg-ids", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "src-msg-id", "topic-id"},
	},
	{
		CLIPath: "chat message reply",
		Aliases: map[string]string{
			"chat":                 "conversation-id",
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
			"ref-message-id":       "ref-msg-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-id", "msg-id", "msg-ids", "name", "open-conversation-ids", "open-message-id", "source", "src-conversation-id", "src-msg-id", "staff-id", "target", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "chat message search",
		Aliases: map[string]string{
			"chat-id":              "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat message search-advanced",
		Aliases: map[string]string{
			"open-conversation-ids": "conversation-ids",
			"user-ids":              "users",
		},
		Blocked: []string{"at-user-ids", "chat-id", "conversation-id", "group-id", "group-ids", "open-conversation-id", "staff-id", "uid", "userid"},
	},
	{
		CLIPath: "chat message send",
		Aliases: map[string]string{
			"chat-id":              "group",
			"file":                 "file-path",
			"open-conversation-id": "group",
			"staff-id":             "user",
			"to-user":              "user",
			"uid":                  "user",
			"user-id":              "user",
			"userid":               "user",
		},
		Blocked: []string{"at-user-ids", "conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target", "user-ids", "users"},
	},
	{
		CLIPath: "chat message send-by-bot",
		Aliases: map[string]string{
			"at-users":             "at-user-ids",
			"chat-id":              "group",
			"open-conversation-id": "group",
			"robot":                "robot-code",
			"user-ids":             "users",
		},
		Blocked:   []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "robot-id", "source", "src-conversation-id", "staff-id", "target", "to-user-id", "uid", "user", "user-id", "userid"},
		Ambiguous: []string{"at-ids"},
	},
	{
		CLIPath: "chat message send-by-webhook",
		Aliases: map[string]string{
			"at-user-ids": "at-users",
		},
	},
	{
		CLIPath: "chat message send-card",
		Aliases: map[string]string{
			"chat":                 "group",
			"chat-id":              "group",
			"conversation-id":      "group",
			"open-conversation-id": "group",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "staff-id", "target", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "chat message set-pin-msg",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
			"message-id":      "msg-id",
			"open-message-id": "msg-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat message set-top-msg",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
			"message-id":      "msg-id",
			"open-message-id": "msg-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat message unset-pin-msg",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
			"message-id":      "msg-id",
			"open-message-id": "msg-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat message unset-top-msg",
		Aliases: map[string]string{
			"chat":            "open-conversation-id",
			"chat-id":         "open-conversation-id",
			"conversation-id": "open-conversation-id",
			"group":           "open-conversation-id",
			"message-id":      "msg-id",
			"open-message-id": "msg-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "message-ids", "msg-ids", "name", "open-conversation-ids", "open-message-ids", "open-task-id", "ref-msg-id", "resource-id", "source", "src-conversation-id", "src-msg-id", "target", "topic-id"},
	},
	{
		CLIPath: "chat mute",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "group-id", "group-ids", "open-conversation-ids"},
	},
	{
		CLIPath: "chat mute-at-all",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat mute-red-envelope",
		Aliases: map[string]string{
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "chat set-top",
		Aliases: map[string]string{
			"chat":                 "conversation-id",
			"chat-id":              "conversation-id",
			"group":                "conversation-id",
			"open-conversation-id": "conversation-id",
		},
		Blocked: []string{"conversation-ids", "dest-conversation-id", "group-id", "group-ids", "group-name", "id", "name", "open-conversation-ids", "source", "src-conversation-id", "target"},
	},
	{
		CLIPath: "contact +dept-members",
		Aliases: map[string]string{
			"keyword":     "dept",
			"keywords":    "dept",
			"name":        "dept",
			"q":           "dept",
			"query":       "dept",
			"search-word": "dept",
		},
		Blocked: []string{"subject", "text", "title"},
	},
	{
		CLIPath: "contact +list-dept-members",
		Aliases: map[string]string{
			"department-ids": "depts",
			"dept-ids":       "depts",
		},
		Blocked: []string{"department-id", "dept", "dept-id", "name", "query"},
	},
	{
		CLIPath: "contact +list-sub-depts",
		Aliases: map[string]string{
			"department":    "dept",
			"department-id": "dept",
			"dept-id":       "dept",
			"parent":        "dept",
			"parent-id":     "dept",
		},
		Blocked: []string{"department-ids", "dept-ids", "depts", "name", "query"},
	},
	{
		CLIPath: "contact +resolve-dept",
		Aliases: map[string]string{
			"keyword":     "name",
			"keywords":    "name",
			"q":           "name",
			"query":       "name",
			"search-word": "name",
		},
		Blocked: []string{"subject", "text", "title"},
	},
	{
		CLIPath: "contact +search-user",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "contact dept list-children",
		Aliases: map[string]string{
			"department":    "dept",
			"department-id": "dept",
			"parent":        "dept",
			"parent-id":     "dept",
		},
		Blocked: []string{"department-ids", "depts", "name", "query"},
	},
	{
		CLIPath: "contact user profile get",
		Aliases: map[string]string{
			"id":      "staff-id",
			"ids":     "staff-id",
			"uid":     "staff-id",
			"user":    "staff-id",
			"user-id": "staff-id",
			"userid":  "staff-id",
		},
		Blocked: []string{"at-user-ids", "name", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "dev app get",
		Aliases: map[string]string{
			"app-id":         "unified-app-id",
			"application-id": "unified-app-id",
		},
		Blocked: []string{"agent-id", "app-secret"},
	},
	{
		CLIPath: "devdoc article search",
		Aliases: map[string]string{
			"current-page": "page",
			"limit":        "size",
			"max-result":   "size",
			"max-results":  "size",
			"page-no":      "page",
			"page-num":     "page",
			"page-size":    "size",
			"per-page":     "size",
			"take":         "size",
			"top":          "size",
		},
		Blocked: []string{"count", "cursor", "page-index", "page-token"},
	},
	{
		CLIPath: "ding +receiver-status",
		Aliases: map[string]string{
			"id": "ding-id",
		},
	},
	{
		CLIPath: "ding message receiver-status",
		Aliases: map[string]string{
			"id":           "ding-id",
			"open-ding-id": "ding-id",
		},
	},
	{
		CLIPath: "ding message send",
		Aliases: map[string]string{
			"robot": "robot-code",
		},
		Blocked: []string{"robot-id"},
	},
	{
		CLIPath: "doc +export-get",
		Blocked: []string{"node"},
	},
	{
		CLIPath: "doc +template-search",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "doc block delete",
		Blocked: []string{"index"},
	},
	{
		CLIPath: "doc block insert",
		Aliases: map[string]string{
			"body":    "text",
			"content": "text",
		},
		Blocked: []string{"before-block-id", "name", "title"},
	},
	{
		CLIPath: "doc block update",
		Aliases: map[string]string{
			"body":    "text",
			"content": "text",
		},
		Blocked: []string{"name", "title"},
	},
	{
		CLIPath: "drive info",
		Aliases: map[string]string{
			"space":        "space-id",
			"workspace":    "space-id",
			"workspace-id": "space-id",
		},
		Blocked: []string{"folder"},
	},
	{
		CLIPath: "drive list",
		Aliases: map[string]string{
			"folder-id": "folder",
		},
		Ambiguous: []string{"space"},
	},
	{
		CLIPath:   "drive upload",
		Ambiguous: []string{"space"},
	},
	{
		CLIPath: "mail +find-mail-user",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "mail folder update",
		Aliases: map[string]string{
			"folder":    "id",
			"folder-id": "id",
		},
		Blocked: []string{"space-id"},
	},
	{
		CLIPath: "mail message search",
		Aliases: map[string]string{
			"subject": "query",
		},
	},
	{
		CLIPath: "mail thread list",
		Aliases: map[string]string{
			"max-result":  "limit",
			"max-results": "limit",
			"page-size":   "limit",
			"per-page":    "limit",
			"size":        "limit",
			"take":        "limit",
			"top":         "limit",
		},
		Blocked: []string{"count", "page"},
	},
	{
		CLIPath: "mail user search",
		Aliases: map[string]string{
			"keywords":    "keyword",
			"q":           "keyword",
			"query":       "keyword",
			"search-word": "keyword",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "oa +list-executed",
		Aliases: map[string]string{
			"max-result":  "limit",
			"max-results": "limit",
			"page-size":   "limit",
			"per-page":    "limit",
			"size":        "limit",
			"take":        "limit",
			"top":         "limit",
		},
		Blocked: []string{"count", "cursor"},
	},
	{
		CLIPath: "oa +search-forms",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "oa approval search-forms",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "report list",
		Aliases: map[string]string{
			"begin":      "start",
			"from":       "start",
			"from-date":  "start",
			"min-time":   "start",
			"since":      "start",
			"start-date": "start",
			"start-time": "start",
			"time-min":   "start",
		},
		Blocked: []string{"date", "time"},
	},
	{
		CLIPath: "report outbox list",
		Blocked: []string{"template-type"},
	},
}

func loadGeneratedParamAliases() []ParamAliasEntry {
	return generatedParamAliases
}
