// Copyright 2026 Alibaba Group
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cli

// reviewedRuntimeSchemaExclusionGroups is the reviewed authority for
// public Cobra leaves intentionally kept outside the stable Agent
// Schema surface. Exact path match only; no prefix or wildcard.
// Each group must be reviewed with a non-empty reason.
var reviewedRuntimeSchemaExclusionGroups = []runtimeSchemaExclusionGroup{
	{
		ID:       "cli-management",
		Reason:   "Local CLI lifecycle, authentication, configuration, and plugin-management commands are user-operated controls rather than stable Agent tools.",
		Reviewed: true,
		Commands: []string{
			"api",
			"auth export",
			"auth import",
			"auth login",
			"auth logout",
			"auth migrate-keychain",
			"auth reset",
			"auth status",
			"completion",
			"config list",
			"doctor",
			"plugin build",
			"plugin config get",
			"plugin config list",
			"plugin config set",
			"plugin config unset",
			"plugin create",
			"plugin dev",
			"plugin disable",
			"plugin enable",
			"plugin info",
			"plugin install",
			"plugin list",
			"plugin remove",
			"plugin validate",
			"profile list",
			"profile switch",
			"profile use",
			"schema",
			"skill get",
			"skill install",
			"skill search",
			"skill setup",
			"upgrade",
			"version",
		},
	},
	{
		ID:       "agoal-out-of-surface",
		Reason:   "The Agoal product remains executable for compatibility but is outside the currently reviewed open-source Agent command surface.",
		Reviewed: true,
		Commands: []string{
			"agoal contract detail",
			"agoal contract fields",
			"agoal contract list",
			"agoal contract update",
			"agoal obj-template create-or-update",
			"agoal obj-template list",
			"agoal report list-statistics",
			"agoal report submit-detail",
			"agoal scorecard detail",
			"agoal scorecard entity-detail",
			"agoal scorecard update",
			"agoal strategy detail",
			"agoal strategy list",
			"agoal strategy update",
			"agoal user objectives",
			"agoal user rules",
		},
	},
	{
		ID:       "compatibility-helpers-pending-review",
		Reason:   "This executable compatibility/helper command has not yet completed stable interface, parameter, and Agent safety review; it must be reviewed before entering the release Catalog.",
		Reviewed: true,
		Commands: []string{
			"calendar acl add",
			"calendar acl delete",
			"calendar book update",
			"contact label get",
			"contact label list",
			"contact label list-members",
			"ding message list",
			"ding message recall-personal",
			"ding message receiver-status",
			"ding message send-by-message",
			"ding message send-personal",
			"mail allow-list add",
			"mail allow-list list",
			"mail allow-list remove",
			"mail auto-reply get",
			"mail auto-reply update",
			"mail block-list add",
			"mail block-list list",
			"mail block-list remove",
			"mail mailbox profile",
			"mail message batch-get",
			"mail message batch-update",
			"mail message verify",
			"mail rule adjust",
			"mail rule create",
			"mail rule delete",
			"mail rule list",
			"mail rule update",
			"mail sent-message recall",
			"mail sent-message recall-detail",
			"mail tag create",
			"mail tag delete",
			"mail tag update",
			"mail thread batch-trash",
			"mail thread batch-update",
			"mail thread list",
			"mail thread trash",
			"mail thread update",
			"oa approval append-task",
			"oa approval ding-info",
			"oa approval revert-activities",
			"oa approval revert-task",
			"oa approval search-forms",
			"todo task list-sub",
			"todo task remove-attachment",
		},
	},
}
